# Streamlit Secrets Configuration
# Add your API keys here for local development
# For production deployment, add these through Streamlit Cloud dashboard

# OpenAI API Key
OPENAI_API_KEY = "your-openai-api-key-here"

# Pinecone API Key  
PINECONE_API_KEY = "your-pinecone-api-key-here"
